/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    Loading: typeof import('./../components/Loading/index.vue')['default']
    MyAoutInput: typeof import('./../components/MyForm/MyAoutInput/index.vue')['default']
    MyAutoInput: typeof import('./../components/MyForm/MyAutoInput/index.vue')['default']
    MyButton: typeof import('./../components/MyForm/MyButton/index.vue')['default']
    MyCascader: typeof import('./../components/MyForm/MyCascader/index.vue')['default']
    MyCheck: typeof import('./../components/MyForm/MyCheck/index.vue')['default']
    MyDete: typeof import('./../components/MyForm/MyDete/index.vue')['default']
    MyForm: typeof import('./../components/MyForm/index.vue')['default']
    MyInput: typeof import('./../components/MyForm/MyInput/index.vue')['default']
    MyNumberInput: typeof import('./../components/MyForm/MyNumberInput/index.vue')['default']
    MyRadio: typeof import('./../components/MyForm/MyRadio/index.vue')['default']
    MySelect: typeof import('./../components/MyForm/MySelect/index.vue')['default']
    MySwitch: typeof import('./../components/MyForm/MySwitch/index.vue')['default']
    MyTable: typeof import('./../components/MyTable/index.vue')['default']
    MyTags: typeof import('./../components/MyForm/MyTags/index.vue')['default']
    MyTransfer: typeof import('./../components/MyForm/MyTransfer/index.vue')['default']
    MyUpload: typeof import('./../components/MyForm/MyUpload/index.vue')['default']
    NAutoComplete: typeof import('naive-ui')['NAutoComplete']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NCascader: typeof import('naive-ui')['NCascader']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NCheckboxGroup: typeof import('naive-ui')['NCheckboxGroup']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDatePicker: typeof import('naive-ui')['NDatePicker']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NDynamicTags: typeof import('naive-ui')['NDynamicTags']
    NFlex: typeof import('naive-ui')['NFlex']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NRadio: typeof import('naive-ui')['NRadio']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTransfer: typeof import('naive-ui')['NTransfer']
    NUpload: typeof import('naive-ui')['NUpload']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default']
  }
}
